name:                advent-of-haskell
version:             0.1.0.0
github:              "githubuser/advent-of-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec

library:
  source-dirs: src

executables:
  q01:
    main:                q01.hs
    source-dirs:         app
  q02:
    main:                q02.hs
    source-dirs:         app
  q03:
    main:                q03.hs
    source-dirs:         app
