name:                advent-of-haskell

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- time
- split

library:
  source-dirs: src

executables:
  q01:
    main:                q01.hs
    source-dirs:         app
  q02:
    main:                q02.hs
    source-dirs:         app
  q03:
    main:                q03.hs
    source-dirs:         app
  q04:
    main:                q04.hs
    source-dirs:         app
  q05:
    main:                q05.hs
    source-dirs:         app
  q06:
    main:                q06.hs
    source-dirs:         app
